/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinal;

/**
 *
 * @author victo
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    private SistemaTickets sistema;

public Ventana(SistemaTickets sistema) {
    initComponents();
    this.sistema = sistema;
    setLocationRelativeTo(null);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        RegisInci = new javax.swing.JButton();
        ListaTic = new javax.swing.JButton();
        GuardArch = new javax.swing.JButton();
        AsigTec = new javax.swing.JButton();
        ReportClien = new javax.swing.JButton();
        CerrarT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        RegisInci.setBackground(new java.awt.Color(255, 0, 0));
        RegisInci.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RegisInci.setText("Registrar Incidencias");
        RegisInci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisInciActionPerformed(evt);
            }
        });

        ListaTic.setBackground(new java.awt.Color(102, 255, 102));
        ListaTic.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ListaTic.setText("Listar Tickets");
        ListaTic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaTicActionPerformed(evt);
            }
        });

        GuardArch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        GuardArch.setText("Guardar en archivo");
        GuardArch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardArchActionPerformed(evt);
            }
        });

        AsigTec.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AsigTec.setText("Asignar Tecnico");
        AsigTec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsigTecActionPerformed(evt);
            }
        });

        ReportClien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ReportClien.setText("Historial Clientes");
        ReportClien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportClienActionPerformed(evt);
            }
        });

        CerrarT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CerrarT.setText("Cerrar Ticket Con Solucion");
        CerrarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarTActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("SELECCIONA LA ACCION A REALIZAR ");

        Salir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Salir.setText("SALIR");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CerrarT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GuardArch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RegisInci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(AsigTec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ListaTic, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ReportClien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(76, 76, 76))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ListaTic)
                    .addComponent(RegisInci))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GuardArch)
                    .addComponent(AsigTec))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReportClien)
                    .addComponent(CerrarT))
                .addGap(41, 41, 41)
                .addComponent(Salir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListaTicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaTicActionPerformed
      VentanaListar dialog = new VentanaListar(this, true, sistema);
dialog.setVisible(true);
    }//GEN-LAST:event_ListaTicActionPerformed

    private void AsigTecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsigTecActionPerformed
       // new VentanaAsignarTec(this, true).setVisible(true);
    }//GEN-LAST:event_AsigTecActionPerformed

    private void ReportClienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportClienActionPerformed
        //new VentanaReportes(this, true).setVisible(true);
    }//GEN-LAST:event_ReportClienActionPerformed

    private void CerrarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarTActionPerformed
       // new VentanaCerrar(this, true).setVisible(true);
    }//GEN-LAST:event_CerrarTActionPerformed

    private void RegisInciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisInciActionPerformed
        VentanaRegistro dialog = new VentanaRegistro(this, true, sistema);
dialog.setVisible(true);

    }//GEN-LAST:event_RegisInciActionPerformed

    private void GuardArchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardArchActionPerformed
     //   new VentanaGuardarArchivo(this, true).setVisible(true);
    }//GEN-LAST:event_GuardArchActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    
        
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AsigTec;
    private javax.swing.JButton CerrarT;
    private javax.swing.JButton GuardArch;
    private javax.swing.JButton ListaTic;
    private javax.swing.JButton RegisInci;
    private javax.swing.JButton ReportClien;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
